### ISSUE TITLE
Plugin Does Not Work With 4.13

### ISSUE THREAD

**Issue by CJRobertson** [ManusVR/Manus-Unreal#14]
I attempted to use the plugin in the new UE 4.13 release but unfortunately I can't get it to compile in any projects. I've attached the output for the error log.

[UE_413_BuildError_Output.txt](https://github.com/ManusVR/Manus-Unreal/files/492050/UE_413_BuildError_Output.txt)

**Comment by Cyx69** [comment]
@CJRobertson
Fixed build for UE4.13.
Files changed:
[https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/ManusVR.Build.cs](https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/ManusVR.Build.cs)
[https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Public/ManusVRAnimInstance.h](https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Public/ManusVRAnimInstance.h)
[https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Private/ManusVRAnimInstance.cpp](https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Private/ManusVRAnimInstance.cpp)
Just replace them and recompile.

**Comment by CJRobertson** [comment]
Updates to the plugin work perfectly. Thank you for the help.
