### ISSUE TITLE
Plugin not working in 4.11

### ISSUE THREAD

**Issue by CJRobertson** [ManusVR/Manus-Unreal#6]
Used the plugin in 4.11 today for the first time.

The plugin compiles no problem but I receive two warnings advising me to upgrade the AnimInstance code to the new API otherwise next release it will no longer compile. I continued on and after getting everything setup I found that the hand models are not moving in game. If I switch back to a 4.9 or 4.10 build I'm good, but 4.11 nothing works. I'm assuming it's because of the modifications to the Animation code in UE4 that was mentioned in the warnings.

[Warning1.txt](https://github.com/ManusVR/Manus-Unreal/files/219862/Warning1.txt)

[Warning2.txt](https://github.com/ManusVR/Manus-Unreal/files/219865/Warning2.txt)

**Comment by Cyx69** [comment]
@CJRobertson 
I have added the support for UE version 4.11 and fixed the issue/warnings. Gloves should now work again.
Files changed:
https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Private/ManusVRAnimInstance.cpp
https://github.com/Cyx69/Manus-Unreal/blob/master/Plugins/ManusVR/Source/ManusVR/Public/ManusVRAnimInstance.h
Just replace them and recompile.

**Comment by CJRobertson** [comment]
Awesome, thank you for the help again.

I'll let you know if everything works on my end soon.

**Comment by Armada651** [comment]
@CJRobertson I'll merge this as soon as you confirm it works on your end.

**Comment by CJRobertson** [comment]
Everything is working 100%! Works in the editor as well as a packaged version of the project so you are good to go for the merging.
