### ISSUE TITLE
New commits cause no connection to PC

### ISSUE THREAD

**Issue by CJRobertson** [ManusVR/Manus-Unreal#9]
I've been noticing changes to the plugin regarding how the gloves communicate with the PC. It seems the Bluetooth ability has been removed and replaced with dongle communication. I'm not sure what that is, but I'm assuming that's what's causing my issue.

The gloves are paired with the computer which I've tried unpairing and repairing. When attempting to use them in a blank project, the included project with the plugin or a already started one, the gloves will not connect to the computer. I can tell this since the LEDs are flashing and not solid.The plugin compiles fine, no warnings or errors.

I am still using an early adopter kit if that matters.

**Comment by Armada651** [comment]
We've recently switch to dongle communication, which we've started rolling out to early adopters and will be the primary means of communication for the Developer Kit.

For now you can simply revert commit 5e897d2724fa5de690e2bc710827257fa0968500 on your local clone to switch back to Bluetooth communication.

**Comment by CJRobertson** [comment]
Oh that's awesome. I already liked how little latency there was, just means it's going to get even better.

I had reverted back to an older commit as soon as I realized the new updates were not working for me so no worries there. Thank you for the help and I guess if need be this 'issue' could get closed.

**Comment by CJRobertson** [comment]
Everything works awesome with the new dongle. Closing the issue.
